const crypto = require('crypto');

const YOUTUBE_SCOPE = 'https://www.googleapis.com/auth/youtube.upload https://www.googleapis.com/auth/youtube.readonly';
function requiredEnv(name) { const value = process.env[name]; if (!value) throw new Error(`${name} is not configured`); return value; }
function redirectUri() { return process.env.GOOGLE_REDIRECT_URI || 'https://socialized-self.vercel.app/api/youtube/callback'; }
function cookieOptions(maxAge = 600) { return `Path=/; Max-Age=${maxAge}; HttpOnly; Secure; SameSite=Lax`; }
function clearCookie(name) { return `${name}=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Lax`; }
function parseCookies(req) { const raw = req.headers.cookie || ''; return Object.fromEntries(raw.split(';').map(v => v.trim()).filter(Boolean).map(v => { const i = v.indexOf('='); return [decodeURIComponent(v.slice(0, i)), decodeURIComponent(v.slice(i + 1))]; })); }
function randomId(bytes = 24) { return crypto.randomBytes(bytes).toString('base64url'); }
function signState(value) { const secret = requiredEnv('SUPABASE_SERVICE_ROLE_KEY'); const sig = crypto.createHmac('sha256', secret).update(value).digest('base64url'); return `${value}.${sig}`; }
function verifyState(signed) { if (!signed || !signed.includes('.')) return false; const i = signed.lastIndexOf('.'); const value = signed.slice(0, i); const sig = signed.slice(i + 1); const expected = crypto.createHmac('sha256', requiredEnv('SUPABASE_SERVICE_ROLE_KEY')).update(value).digest('base64url'); if (sig.length !== expected.length || !crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(expected))) return false; try { return Date.now() - Number(JSON.parse(Buffer.from(value, 'base64url').toString()).createdAt) < 10 * 60 * 1000; } catch { return false; } }
function key() { return crypto.createHash('sha256').update(requiredEnv('SUPABASE_SERVICE_ROLE_KEY')).digest(); }
function encryptSecret(text) { const iv = crypto.randomBytes(12); const cipher = crypto.createCipheriv('aes-256-gcm', key(), iv); const encrypted = Buffer.concat([cipher.update(text, 'utf8'), cipher.final()]); return [iv, cipher.getAuthTag(), encrypted].map(x => x.toString('base64url')).join('.'); }
function decryptSecret(value) { const [ivB64, tagB64, dataB64] = String(value).split('.'); const decipher = crypto.createDecipheriv('aes-256-gcm', key(), Buffer.from(ivB64, 'base64url')); decipher.setAuthTag(Buffer.from(tagB64, 'base64url')); return Buffer.concat([decipher.update(Buffer.from(dataB64, 'base64url')), decipher.final()]).toString('utf8'); }
async function supabase(path, options = {}) { const base = requiredEnv('SUPABASE_URL').replace(/\/$/, ''); const keyValue = requiredEnv('SUPABASE_SERVICE_ROLE_KEY'); const response = await fetch(`${base}/rest/v1/${path}`, { ...options, headers: { apikey: keyValue, Authorization: `Bearer ${keyValue}`, 'Content-Type': 'application/json', ...(options.headers || {}) } }); const text = await response.text(); let data = null; try { data = text ? JSON.parse(text) : null; } catch { data = text; } if (!response.ok) throw new Error(typeof data === 'string' ? data : data?.message || data?.error || `Supabase HTTP ${response.status}`); return data; }
async function googleToken(params) { const body = new URLSearchParams({ client_id: requiredEnv('GOOGLE_CLIENT_ID'), client_secret: requiredEnv('GOOGLE_CLIENT_SECRET'), redirect_uri: redirectUri(), ...params }); const r = await fetch('https://oauth2.googleapis.com/token', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body }); const data = await r.json(); if (!r.ok) throw new Error(data.error_description || data.error || 'Google token exchange failed'); return data; }
module.exports = { YOUTUBE_SCOPE, requiredEnv, redirectUri, cookieOptions, clearCookie, parseCookies, randomId, signState, verifyState, encryptSecret, decryptSecret, supabase, googleToken };
